version: '3'

services:
  postgres:
    image: postgres:15
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: . # Changed from ./backend
      dockerfile: Dockerfile # Assumes Dockerfile is in the root
    container_name: inventory-backend
    env_file: .env # Added for JWT_SECRET and other secrets
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/inventory
      # JWT_SECRET removed, should be in .env
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: . # Changed from ./frontend, assuming root for now
      dockerfile: Dockerfile.frontend # Placeholder, needs to be created
    container_name: inventory-frontend
    env_file: .env # Added for VITE_API_URL and other potential frontend env vars
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
